---

- hosts: all
  become: true

  tasks:

  - name: Install Apache & PHP Packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
