---

- hosts: all
  become: true
  
  tasks:
  - name: Install Updates (CentOS)
    tags: always
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true

  tasks:
  - name: Install Apache2 & PHP Packages for Ubuntu Servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache & PHP Packages for CentOS Servers
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Set Time-Zone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Start HTTPD (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Copy Default HTML File for Site
    tags: apache,apache2,httpd
    copy:
      src: ~/ansible_3/php_file/index.php
      dest: /var/www/html/
      owner: root
      group: root
      mode: 0644

- hosts: file_servers
  become: true

  tasks:
  - name: Install Samba Package
    tags: samba
    package:
      name: samba
      state: latest
